channels:
- conda-forge
dependencies:
- python=3.8.12
- pip
- pip:
  - mlflow
  - pandas==1.3.4
  - psutil==5.8.0
  - scikit-learn==1.0.1
  - typing-extensions==3.10.0.2
  - xgboost==1.4.2
name: mlflow-env
