base:
  project: mlops
  random_state: 42
  target_col: "fare_amount"

GPU_cluster:
  max_memory: "48"

split_data:
  valid_test_ratio: 0.2

train:
  save_model: True
  params:
    booster: "gbtree"
    eval_metric: "rmse"
    tree_method: "gpu_hist"
    objective: "reg:squarederror"
    min_child_weight: 1
    colsample_bytree: 0.7
    learning_rate: 0.05
  early_stopping_rounds: 100
  num_boost_round: 10000
  verbose_eval: 100

test:
  model_name: "xgboost"
  model_extension: ".model"

triton:
  ip: "13.92.226.55"
  http_port: "8000"
  grpc_port: "8001"
  dtype: "float32"