base:
  project: mlops
  random_state: 42
  target_col: "fare_amount"

GPU_cluster:
  max_memory: "48"

load_data:
  data_dir: "../data"
  train_data_name: "train.csv"
  test_data_name: "test.csv"

split_data:
  split_ratio: 0.2

train:
  save_model: True
  params:
    booster: "gbtree"
    eval_metric: "rmse"
    tree_method: "gpu_hist"
    objective: "reg:squarederror"
    min_child_weight: 1
    colsample_bytree: 0.7
    learning_rate: 0.05
  early_stopping_rounds: 100
  num_boost_round: 100000
  verbose_eval: 100

test:
  saved_model_dir: "saved_models"
  model_name: "xgboost"
  model_extension: ".model"

mlflow:
  artifacts_dir: artifacts
  experiment_name: xgboost_regression_gpu
  run_name: mlops
  registered_model_name: xgboost_nyc_taxi_fare_prediction
  remote_server_uri: http://13.92.226.55:8003

triton:
  ip: "13.92.226.55"
  http_port: "8000"
  grpc_port: "8001"
  dtype: "float32"